#!/bin/bash
#use this file to write your runner application

#this application should take the x.sum files on /files
#and call summer.py using as parameters the number on x.sum 
#when called this application will add a file named a+b.summed to /allsums
#with the output from summer.py as content

arquivo=$*

a=$(cat $arquivo)

saida=$(python summer.py $a)

echo $saida

saida=($saida)
tam=${#saida[@]}
resultado=${saida[$(($tam - 1))]}

arquivos=($(ls))
quantArq=$((${#arquivos[@]} -1))

while [ "$quantArq" -ge 0 ]  
do
     if [ "${arquivos[$quantArq]}" == "allsums" ];
     then
	quantArq=-2
        break
     else
        quantArq=$(($quantArq - 1)) 	
     fi
         
done
if [ "$quantArq" == -1 ];
then
     mkdir allsums
     echo $resultado > allsums/$resultado.summed
else
     echo $resultado > allsums/$resultado.summed  
fi


     
    
